*&---------------------------------------------------------------------*
*& Include          ZTEST_P_TOP
*&---------------------------------------------------------------------*

TABLES : EKKO , EKPO, ZEKKO_GCO , ZEKPO_GCO.

DATA :GT_ZEKKO_GCO TYPE TABLE OF ZEKKO_GCO.
DATA :GS_ZEKKO_GCO LIKE LINE OF GT_ZEKKO_GCO.

DATA :GT_ZEKPO_GCO TYPE TABLE OF ZEKPO_GCO.


      DATA : O_SPLITTER_MAIN TYPE REF TO CL_GUI_SPLITTER_CONTAINER.
      DATA : O_CONTAINER_LEFT TYPE REF TO CL_GUI_CONTAINER.
      DATA : O_CONTAINER_RIGHT TYPE REF TO CL_GUI_CONTAINER.
      DATA : O_SALV_LEFT TYPE REF TO CL_SALV_TABLE.
      DATA : O_SALV_RIGHT TYPE REF TO CL_SALV_TABLE.
      DATA : O_EVENTS TYPE REF TO CL_SALV_EVENTS_TABLE.